document.writeln("<header class=\"navbar\">");
document.writeln("    <div class=\"container\">");
document.writeln("        <div class=\"navbar-header\">");
document.writeln("            <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">");
document.writeln("                <span class=\"sr-only\">Toggle navigation</span>");
document.writeln("                <span class=\"icon-bar\"></span>");
document.writeln("                <span class=\"icon-bar\"></span>");
document.writeln("                <span class=\"icon-bar\"></span>");
document.writeln("            </button>");
document.writeln("            <a class=\"navbar-brand\" href=\"http://2016.igem.org\"><img src=\"img/logo.png\" style=\"height:32px;margin-top:-5px;\"></a>");
document.writeln("        </div>");
document.writeln("        <div id=\"navbar\" class=\"collapse navbar-collapse\">");
document.writeln("            <ul class=\"nav navbar-nav navbar-right\">");
document.writeln("                <li><a href=\"Home.html\">Home</a></li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a class=\"dropdown-toggle\" href=\"Project.html\">Project</a>");
document.writeln("                    <ul class=\"dropdown-menu dropdown-right\">");
document.writeln("                        <li><a href=\"Project.html#Intestinal_Disease\">Intestinal Disease</a></li>");
document.writeln("                        <li><a href=\"Project.html#EGF_Expression\">EGF Expression</a></li>");
document.writeln("                        <li><a href=\"Project.html#Therapeutic_Biofilm\">Therapeutic Biofilm</a></li>");
document.writeln("                        <li><a href=\"Project.html#NO_Sensor\">NO Sensor</a></li>");
document.writeln("                        <li><a href=\"Project.html#Quorum_Sensing\">Quorum Sensing</a></li>");
document.writeln("                        <li><a href=\"Project.html#Kill_Switch\">Kill Switch</a></li>");
document.writeln("                        <li><a href=\"Project.html#Warship\">Warship</a></li>");
document.writeln("                        <li><a href=\"Project.html#Model\">Model</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a class=\"dropdown-toggle\" href=\"Lab_Work.html\">Lab Work</a>");
document.writeln("                    <ul class=\"dropdown-menu dropdown-right\">");
document.writeln("                        <li><a href=\"Lab_Work.html#Parts\">Parts</a></li>");
document.writeln("                        <li><a href=\"Lab_Work.html#Safety\">Safety</a></li>");
document.writeln("                        <li><a href=\"Lab_Work.html#Protocols\">Protocols</a></li>");
document.writeln("                        <li><a href=\"Lab_Work.html#Notebook\">Notebook</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a class=\"dropdown-toggle\" href=\"Human_Practice.html\">Human Practice</a>");
document.writeln("                    <ul class=\"dropdown-menu dropdown-right\">");
document.writeln("                        <li><a href=\"Human_Practice.html#Introduction\">Introduction</a></li>");
document.writeln("                        <li><a href=\"Human_Practice.html#Interviews\">Interviews</a></li>");
document.writeln("                        <li><a href=\"Human_Practice.html#Survey\">Survey</a></li>");
document.writeln("                        <li><a href=\"Human_Practice.html#Social Media\">Social Media</a></li>");
document.writeln("                        <li><a href=\"Human_Practice.html#HUST_Cheering\">HUST-Cheering</a></li>");
document.writeln("                        <li><a href=\"Human_Practice.html#iDPI\">iDPI</a></li>");
document.writeln("                        <li><a href=\"Human_Practice.html#Poster\">Poster</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a class=\"dropdown-toggle\" href=\"Collaborations.html\">Collaborations</a>");
document.writeln("                    <ul class=\"dropdown-menu dropdown-right\">");
document.writeln("                        <li><a href=\"Collaborations.html#SYSU_MEDICINE\">SYSU-MEDICINE</a></li>");
document.writeln("                        <li><a href=\"Collaborations.html#FAFU_CHINA\">FAFU-CHINA</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a class=\"dropdown-toggle\" href=\"About_Us.html\">About Us</a>");
document.writeln("                    <ul class=\"dropdown-menu dropdown-right\">");
document.writeln("                        <li><a href=\"About_Us.html#Team Roster\">Team Roster</a></li>");
document.writeln("                        <li><a href=\"About_Us.html#Acknowledgement\">Acknowledgement</a></li>");
document.writeln("                        <li><a href=\"About_Us.html#Attributions\">Attributions</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Judging</a>");
document.writeln("                    <ul class=\"dropdown-menu dropdown-right\">");
document.writeln("                        <li><a href=\"Judging/Attributions.html\">Attributions</a></li>");
document.writeln("                        <li><a href=\"Judging/Collaborations.html\">Collaborations</a></li>");
document.writeln("                        <li><a href=\"Judging/HP/Silver.html\">HP Silver</a></li>");
document.writeln("                        <li><a href=\"Judging/HP/Gold.html\">HP Gold</a></li>");
document.writeln("                        <li><a href=\"Judging/Description.html\">Description</a></li>");
document.writeln("                        <li><a href=\"Judging/Proof.html\">Proof</a></li>");
document.writeln("                        <li><a href=\"Judging/Demonstrate.html\">Demonstrate</a></li>");
document.writeln("                        <li><a href=\"Judging/Integrated_Practices.html\">Integrated Practices</a></li>");
document.writeln("                        <li><a href=\"Judging/Model.html\">Model</a></li>");
document.writeln("                        <li><a href=\"Judging/Hardware.html\">Hardware</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div> ");
document.writeln("</header>");